### ISSUE TITLE
Buying doorman

### ISSUE THREAD

**Issue by gregmag** [AzonInc/Doorman#10]
Hi, i am interested to buy a Doorman S3 ...
Can you send it to switzerland ? How much does it costs ?
Thank you and congratulation for this amazing developement ?

**Comment by AzonInc** [comment]
Hi, thanks for ur interest. Just send me a mail to discuss further details :)
flo@azon.ai

**Comment by AzonInc** [comment]
Are you still interested?

**Comment by pumabaer** [comment]
Hello, I would also be interested in a circuit board. 
What do you want for it?

**Comment by AzonInc** [comment]
Hi,

for a the fully assembled Doorman it's 30€ + shipping.

Best regards
Flo

Am Donnerstag, 25. Juli 2024 22:22 CEST, schrieb pumabaer ***@***.***>:
 
 
Hello, I would also be interested in a circuit board.
What do you want for it?
