### ISSUE TITLE
Add a Tag for FW version "2024.8.5"

### ISSUE THREAD

**Issue by m4n0v31** [AzonInc/Doorman#28]
### Description

Hi,
I reached a good configuration based on the FW 2024.8.5 (around 28 of August).
I wanted to do some changes, but I can't, as the new dev features and structural changes made their way into master.
Would it be possible to have a tag for the version above?

Thank you

**Comment by AzonInc** [comment]
Oh yea sorry.

I will do that when I'm back home.
The commit hash is
 `dd42160867f47b98d6e0a0b0f74b9647e1fc8b3e`

**Comment by AzonInc** [comment]
Tag created https://github.com/AzonInc/Doorman/releases/tag/2024.8.5
